name: UAT Bug Report
description: Report a bug found during UAT testing
title: "[UAT Bug]: "
labels: ["bug", "uat"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for testing! Please fill out this form to report a bug.

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of the app has the bug?
      options:
        - Login / Signup
        - Dogs (add, edit, delete)
        - Boardings (add, edit, delete)
        - Boarding Matrix / Calendar
        - Payroll / Payments
        - Settings
        - Other
    validations:
      required: true

  - type: input
    id: requirement
    attributes:
      label: Requirement ID (if known)
      description: "e.g., REQ-041"
      placeholder: "REQ-XXX"
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: "When I clicked 'Mark as Paid', nothing happened..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
      description: What did you expect to happen?
      placeholder: "The payment should have been recorded and shown in history..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to Payroll page
        2. Click 'Mark as Paid' for Kate
        3. Select all dates
        4. Click 'Confirm Payment'
        5. Nothing happens
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How bad is this bug?
      options:
        - Blocker - Can't use the feature at all
        - Major - Feature works but has significant issues
        - Minor - Small issue, workaround exists
        - Cosmetic - Visual issue only
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device
      options:
        - Desktop (Chrome)
        - Desktop (Safari)
        - Desktop (Firefox)
        - iPhone
        - Android
        - Other
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag and drop screenshots here if helpful
    validations:
      required: false
