name: UAT Feedback
description: General feedback or suggestions from UAT testing
title: "[UAT Feedback]: "
labels: ["feedback", "uat"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feedback! This helps us improve the app.

  - type: dropdown
    id: feedback-type
    attributes:
      label: Type of feedback
      options:
        - Confusing UI / UX
        - Missing feature
        - Performance issue
        - Suggestion / Improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      options:
        - Login / Signup
        - Dogs
        - Boardings
        - Boarding Matrix / Calendar
        - Payroll / Payments
        - Settings
        - General / Overall
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: Your feedback
      description: What would you like to share?
      placeholder: "It would be easier if..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement (optional)
      description: How would you improve this?
    validations:
      required: false
